language: r

sudo: required

before_install:
- sudo apt-get install libv8-dev

r_binary_install:
 - leaflet

r_github_packages:
 - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: change
    on_failure: change
  slack: ropensci:Uk8Kn3U3ngRV1p2YxLvXbQgw
