language: r
sudo: false
cache: packages

r_binary_install:
 - leaflet

addons:
  apt:
    packages:
      - libv8-dev

r_github_packages:
 - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: change
    on_failure: change
  slack: ropensci:Uk8Kn3U3ngRV1p2YxLvXbQgw
