language: r

r_packages:
 - maps

r_github_packages:
 - jimhester/covr
 - rstudio/leaflet

after_success:
  - Rscript -e 'library(covr); coveralls()'

notifications:
  email:
    on_success: change
    on_failure: change
  slack: ropensci:Uk8Kn3U3ngRV1p2YxLvXbQgw
